# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4449cb51e748fd6043cd2d8002b66527422a92ebbb5e83208d16a78086215709a0adbae91621b10105f456492ab46d3290aaebfeeebc3cd2cd72a2daf615dd22

test:
  secret_key_base: ab373aeb73fb2de8aaf916f3edd86c355ea555a37d26f2c7deef9ea2be41330b34941ef0f862ce1b05ea1c26cbf7390246f9d0fc180c31bfdab294188eb4aef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
